# Shell
shell zsh

# Font
font_family      family="JetBrainsMono Nerd Font" style="ExtraLight"
font_size        16.0
modify_font      cell_width 90%
modify_font      cell_height 100%
text_composition_strategy   legacy

# Cursor
cursor_shape          beam
cursor_blink_interval 1
cursor_stop_blinking_after 0

# Window
window_padding_width 0
hide_window_decorations no
confirm_os_window_close 0
single_window_instance true

# Appearance
background_opacity 1
dynamic_background_opacity yes

# Performance
repaint_rate 120

# Wayland
# wayland_titlebar_color background
linux_display_server x11

# Keybindings
map ctrl+v paste_from_clipboard
map alt+- change_font_size all -1.0
map alt+= change_font_size all +1.0
map F11 toggle_fullscreen
map ctrl+shift+z remote_control set-background-opacity --toggle=yes 0.9
map alt+enter send_text normal \x1b


# Theme
include rose-pine.conf
